version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - FLASK_ENV=development
            - FLASK_DEBUG=1
        volumes:
            - ./backend:/app
        depends_on:
            - redis

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_API_URL=http://localhost:5000
        depends_on:
            - backend

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
